apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-leak
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /api/internal/isReady
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 100m
      memory: 32Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  ingresses:
    - "https://leak.ansatt.nav.no"